version: '2'

services:
  dev:
    build: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD:/workspace
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    working_dir: /workspace
